#!/bin/bash

# Instalação do MySQL Server
sudo apt update
sudo apt install mysql-server -y

# Configuração do MySQL Server
sudo systemctl start mysql
sudo systemctl enable mysql

# Configuração inicial do MySQL
sudo mysql_secure_installation

# Criando banco de dados e usuário do Zabbix
sudo mysql -u root -p <<EOF
CREATE DATABASE zabbix CHARACTER SET utf8 COLLATE utf8_bin;
GRANT ALL PRIVILEGES ON zabbix.* TO 'murilo'@'localhost' IDENTIFIED BY 'Ti@Serg@31';
FLUSH PRIVILEGES;
EXIT;
EOF

# Instalação do repositório do Zabbix
wget https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb
sudo dpkg -i zabbix-release_5.4-1+ubuntu20.04_all.deb
sudo apt update

# Instalação do Zabbix Server, Frontend, Agent e Banco de Dados
sudo apt install zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-agent -y

# Importando o esquema e os dados iniciais para o banco de dados do Zabbix
sudo zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | sudo mysql -u zabbix -p zabbix

# Configuração do Zabbix Server
sudo nano /etc/zabbix/zabbix_server.conf

# Altere as seguintes linhas (se necessário):
# DBHost=localhost
# DBName=zabbix
# DBUser=murilo
# DBPassword=Ti@Serg@31

# Configuração do PHP para o Frontend do Zabbix
sudo nano /etc/zabbix/apache.conf

# Altere a seguinte linha (se necessário):
# php_value date.timezone America/Sao_Paulo

# Reiniciando o serviço Apache e Zabbix Server
sudo systemctl restart apache2
sudo systemctl restart zabbix-server

# Habilitando o serviço Zabbix Agent
sudo systemctl enable zabbix-agent

# Reiniciando o serviço Zabbix Agent
sudo systemctl restart zabbix-agent

echo "A instalação do MySQL e Zabbix foi concluída com sucesso!"
